<div class="store-wallpaper" aria-hidden="true">
    <svg class="store-icon-defs" aria-hidden="true" focusable="false">
        <symbol id="store-gamepad" viewBox="0 0 24 24">
            <path d="M7 8h10a4 4 0 0 1 3.8 5.2l-1 3.2a2.5 2.5 0 0 1-4.1 1l-2.1-2.1h-3.2l-2.1 2.1a2.5 2.5 0 0 1-4.1-1l-1-3.2A4 4 0 0 1 7 8Z" />
            <path d="M8 11v4M6 13h4M16 12h.01M18 14h.01" />
        </symbol>
    </svg>
    <div class="store-wallpaper-row">
        <span class="store-wordmark store-steam"><b>ST</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>STEAM</span><span class="store-wordmark store-epic"><b>E</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>EPIC GAMES</span><span class="store-wordmark store-gog"><b>G</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>GOG.COM</span><span class="store-wordmark store-playstation"><b>PS</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>PLAYSTATION STORE</span><span class="store-wordmark store-xbox"><b>X</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>XBOX STORE</span><span class="store-wordmark store-nintendo"><b>N</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>NINTENDO eSHOP</span><span class="store-wordmark store-itch"><b>i</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>ITCH.IO</span>
    </div>
    <div class="store-wallpaper-row">
        <span class="store-wordmark store-humble"><b>H</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>HUMBLE STORE</span><span class="store-wordmark store-gog"><b>G</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>GOG.COM</span><span class="store-wordmark store-steam"><b>ST</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>STEAM</span><span class="store-wordmark store-nintendo"><b>N</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>NINTENDO eSHOP</span><span class="store-wordmark store-epic"><b>E</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>EPIC GAMES</span><span class="store-wordmark store-itch"><b>i</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>ITCH.IO</span><span class="store-wordmark store-xbox"><b>X</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>XBOX STORE</span>
    </div>
    <div class="store-wallpaper-row">
        <span class="store-wordmark store-playstation"><b>PS</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>PLAYSTATION STORE</span><span class="store-wordmark store-itch"><b>i</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>ITCH.IO</span><span class="store-wordmark store-xbox"><b>X</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>XBOX STORE</span><span class="store-wordmark store-steam"><b>ST</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>STEAM</span><span class="store-wordmark store-humble"><b>H</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>HUMBLE STORE</span><span class="store-wordmark store-gog"><b>G</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>GOG.COM</span><span class="store-wordmark store-epic"><b>E</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>EPIC GAMES</span>
    </div>
    <div class="store-wallpaper-row">
        <span class="store-wordmark store-nintendo"><b>N</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>NINTENDO eSHOP</span><span class="store-wordmark store-epic"><b>E</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>EPIC GAMES</span><span class="store-wordmark store-playstation"><b>PS</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>PLAYSTATION STORE</span><span class="store-wordmark store-humble"><b>H</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>HUMBLE STORE</span><span class="store-wordmark store-steam"><b>ST</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>STEAM</span><span class="store-wordmark store-xbox"><b>X</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>XBOX STORE</span><span class="store-wordmark store-gog"><b>G</b><svg class="store-icon" aria-hidden="true"><use href="#store-gamepad"></use></svg>GOG.COM</span>
    </div>
</div>